release:
  github:
    owner: gleich
    name: nuke
  prerelease: auto
before:
  hooks:
    - go mod download
builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
brews:
  - tap:
      owner: gleich
      name: homebrew-taps
    folder: Formula
    homepage: 'https://github.com/gleich/nuke'
    description: '☢️ Force quit all applications with one terminal command'
    commit_author:
      name: gleich
      email: matthewgleich@gmail.com
    install: bin.install "nuke"
